// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrdersApi.models;

namespace OrdersApi.Migrations
{
    [DbContext(typeof(AppOrdersContext))]
    partial class AppOrdersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Orders")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 844m,
                            Name = "order1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1688m,
                            Name = "order2"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2532m,
                            Name = "order3"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3376m,
                            Name = "order4"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 4220m,
                            Name = "order5"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 5064m,
                            Name = "order6"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 5908m,
                            Name = "order7"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 6752m,
                            Name = "order8"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 7596m,
                            Name = "order9"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 8440m,
                            Name = "order10"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 9284m,
                            Name = "order11"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 10128m,
                            Name = "order12"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 10972m,
                            Name = "order13"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 11816m,
                            Name = "order14"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 12660m,
                            Name = "order15"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 13504m,
                            Name = "order16"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 14348m,
                            Name = "order17"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 15192m,
                            Name = "order18"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 16036m,
                            Name = "order19"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 16880m,
                            Name = "order20"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 17724m,
                            Name = "order21"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 18568m,
                            Name = "order22"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 19412m,
                            Name = "order23"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 20256m,
                            Name = "order24"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 21100m,
                            Name = "order25"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 21944m,
                            Name = "order26"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 22788m,
                            Name = "order27"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 23632m,
                            Name = "order28"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 24476m,
                            Name = "order29"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 25320m,
                            Name = "order30"
                        },
                        new
                        {
                            Id = 31,
                            Amount = 26164m,
                            Name = "order31"
                        },
                        new
                        {
                            Id = 32,
                            Amount = 27008m,
                            Name = "order32"
                        },
                        new
                        {
                            Id = 33,
                            Amount = 27852m,
                            Name = "order33"
                        },
                        new
                        {
                            Id = 34,
                            Amount = 28696m,
                            Name = "order34"
                        },
                        new
                        {
                            Id = 35,
                            Amount = 29540m,
                            Name = "order35"
                        },
                        new
                        {
                            Id = 36,
                            Amount = 30384m,
                            Name = "order36"
                        },
                        new
                        {
                            Id = 37,
                            Amount = 31228m,
                            Name = "order37"
                        },
                        new
                        {
                            Id = 38,
                            Amount = 32072m,
                            Name = "order38"
                        },
                        new
                        {
                            Id = 39,
                            Amount = 32916m,
                            Name = "order39"
                        },
                        new
                        {
                            Id = 40,
                            Amount = 33760m,
                            Name = "order40"
                        },
                        new
                        {
                            Id = 41,
                            Amount = 34604m,
                            Name = "order41"
                        },
                        new
                        {
                            Id = 42,
                            Amount = 35448m,
                            Name = "order42"
                        },
                        new
                        {
                            Id = 43,
                            Amount = 36292m,
                            Name = "order43"
                        },
                        new
                        {
                            Id = 44,
                            Amount = 37136m,
                            Name = "order44"
                        },
                        new
                        {
                            Id = 45,
                            Amount = 37980m,
                            Name = "order45"
                        },
                        new
                        {
                            Id = 46,
                            Amount = 38824m,
                            Name = "order46"
                        },
                        new
                        {
                            Id = 47,
                            Amount = 39668m,
                            Name = "order47"
                        },
                        new
                        {
                            Id = 48,
                            Amount = 40512m,
                            Name = "order48"
                        },
                        new
                        {
                            Id = 49,
                            Amount = 41356m,
                            Name = "order49"
                        },
                        new
                        {
                            Id = 50,
                            Amount = 42200m,
                            Name = "order50"
                        },
                        new
                        {
                            Id = 51,
                            Amount = 43044m,
                            Name = "order51"
                        },
                        new
                        {
                            Id = 52,
                            Amount = 43888m,
                            Name = "order52"
                        },
                        new
                        {
                            Id = 53,
                            Amount = 44732m,
                            Name = "order53"
                        },
                        new
                        {
                            Id = 54,
                            Amount = 45576m,
                            Name = "order54"
                        },
                        new
                        {
                            Id = 55,
                            Amount = 46420m,
                            Name = "order55"
                        },
                        new
                        {
                            Id = 56,
                            Amount = 47264m,
                            Name = "order56"
                        },
                        new
                        {
                            Id = 57,
                            Amount = 48108m,
                            Name = "order57"
                        },
                        new
                        {
                            Id = 58,
                            Amount = 48952m,
                            Name = "order58"
                        },
                        new
                        {
                            Id = 59,
                            Amount = 49796m,
                            Name = "order59"
                        },
                        new
                        {
                            Id = 60,
                            Amount = 50640m,
                            Name = "order60"
                        },
                        new
                        {
                            Id = 61,
                            Amount = 51484m,
                            Name = "order61"
                        },
                        new
                        {
                            Id = 62,
                            Amount = 52328m,
                            Name = "order62"
                        },
                        new
                        {
                            Id = 63,
                            Amount = 53172m,
                            Name = "order63"
                        },
                        new
                        {
                            Id = 64,
                            Amount = 54016m,
                            Name = "order64"
                        },
                        new
                        {
                            Id = 65,
                            Amount = 54860m,
                            Name = "order65"
                        },
                        new
                        {
                            Id = 66,
                            Amount = 55704m,
                            Name = "order66"
                        },
                        new
                        {
                            Id = 67,
                            Amount = 56548m,
                            Name = "order67"
                        },
                        new
                        {
                            Id = 68,
                            Amount = 57392m,
                            Name = "order68"
                        },
                        new
                        {
                            Id = 69,
                            Amount = 58236m,
                            Name = "order69"
                        },
                        new
                        {
                            Id = 70,
                            Amount = 59080m,
                            Name = "order70"
                        },
                        new
                        {
                            Id = 71,
                            Amount = 59924m,
                            Name = "order71"
                        },
                        new
                        {
                            Id = 72,
                            Amount = 60768m,
                            Name = "order72"
                        },
                        new
                        {
                            Id = 73,
                            Amount = 61612m,
                            Name = "order73"
                        },
                        new
                        {
                            Id = 74,
                            Amount = 62456m,
                            Name = "order74"
                        },
                        new
                        {
                            Id = 75,
                            Amount = 63300m,
                            Name = "order75"
                        },
                        new
                        {
                            Id = 76,
                            Amount = 64144m,
                            Name = "order76"
                        },
                        new
                        {
                            Id = 77,
                            Amount = 64988m,
                            Name = "order77"
                        },
                        new
                        {
                            Id = 78,
                            Amount = 65832m,
                            Name = "order78"
                        },
                        new
                        {
                            Id = 79,
                            Amount = 66676m,
                            Name = "order79"
                        },
                        new
                        {
                            Id = 80,
                            Amount = 67520m,
                            Name = "order80"
                        },
                        new
                        {
                            Id = 81,
                            Amount = 68364m,
                            Name = "order81"
                        },
                        new
                        {
                            Id = 82,
                            Amount = 69208m,
                            Name = "order82"
                        },
                        new
                        {
                            Id = 83,
                            Amount = 70052m,
                            Name = "order83"
                        },
                        new
                        {
                            Id = 84,
                            Amount = 70896m,
                            Name = "order84"
                        },
                        new
                        {
                            Id = 85,
                            Amount = 71740m,
                            Name = "order85"
                        },
                        new
                        {
                            Id = 86,
                            Amount = 72584m,
                            Name = "order86"
                        },
                        new
                        {
                            Id = 87,
                            Amount = 73428m,
                            Name = "order87"
                        },
                        new
                        {
                            Id = 88,
                            Amount = 74272m,
                            Name = "order88"
                        },
                        new
                        {
                            Id = 89,
                            Amount = 75116m,
                            Name = "order89"
                        },
                        new
                        {
                            Id = 90,
                            Amount = 75960m,
                            Name = "order90"
                        },
                        new
                        {
                            Id = 91,
                            Amount = 76804m,
                            Name = "order91"
                        },
                        new
                        {
                            Id = 92,
                            Amount = 77648m,
                            Name = "order92"
                        },
                        new
                        {
                            Id = 93,
                            Amount = 78492m,
                            Name = "order93"
                        },
                        new
                        {
                            Id = 94,
                            Amount = 79336m,
                            Name = "order94"
                        },
                        new
                        {
                            Id = 95,
                            Amount = 80180m,
                            Name = "order95"
                        },
                        new
                        {
                            Id = 96,
                            Amount = 81024m,
                            Name = "order96"
                        },
                        new
                        {
                            Id = 97,
                            Amount = 81868m,
                            Name = "order97"
                        },
                        new
                        {
                            Id = 98,
                            Amount = 82712m,
                            Name = "order98"
                        },
                        new
                        {
                            Id = 99,
                            Amount = 83556m,
                            Name = "order99"
                        },
                        new
                        {
                            Id = 100,
                            Amount = 84400m,
                            Name = "order100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
